from django.urls import path, include
from .views import *
from rest_framework.routers import DefaultRouter
from knox.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

# Creating a DefaultRouter for automatic URL routing
router = DefaultRouter(trailing_slash=False)
router.register('student_info/?', StudentInfoViewSet, basename='student_info'),
router.register('class_info', StudentClassInfoViewSet, basename='class_info'),
router.register('attendance', AttendanceViewSet, basename='attendance'),

# URL patterns for the API endpoints
urlpatterns = [
    # Including the URLs generated by the DefaultRouter
    path('', include(router.urls)),
    # Endpoint for user registration
    path('api/register', RegisterAPI.as_view(), name='register'),
    # Endpoint for user login
    path('api/login', LoginView.as_view()),
    # Endpoint for user logout
    path('api/logout', LogoutView.as_view(), name='knox_logout'),
]

# Adding URL patterns for serving media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
